version: 2.1

orbs:
  node: circleci/node

jobs:
  build-test-and-notify:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm test
Workflows:
  build-and-notify:
    jobs:
      -built-test-and-notify