version: 2.1

orbs:
  node: circleci/node@4.7.0
  slack: circleci/slack@4.4.4

commands:
  # Parameterize notifications by status
  slack-success:
    steps:
      - slack/notify:
          event: pass
          mentions: '@channel'
          template: basic_success_1

  slack-fail:
    steps:
      - slack/notify:
          event: fail
          mentions: "@channel"
          template: basic_fail_1

jobs:
  # For each independent test job or any other type of job ran in parallel, setup notifications for failure only
  # This will ensure that notifications will be sent only for failed jobs
  build-test-and-notify:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run: npm test
      - slack-fail
      
  build-test-and-notify-2:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run: npm test
      - slack-fail

  build-test-and-notify-3:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Create Error
          command: sed -i 's/Hello/Goodbye/g' test/app.e2e-spec.ts
      - run: npm test
      - slack-fail

  # Setup a workflow-success job for notification sending upon successful completion of all upstream jobs
  # From here you can setup an Approval step or automatically continue pipeline based on success status
  workflow-success:
    executor:
      name: node/default
    steps:
      - run:
          name: Success
          # This exit command it utilized to trigger a success status for notification delivery
          command: | 
            exit 0
      - slack-success
workflows:
  build-and-notify:
    jobs:
      # Setup test jobs in Fan-out process
      - build-test-and-notify:
          context: slack-notifications
      - build-test-and-notify-2:
          context: slack-notifications
      - build-test-and-notify-3:
          context: slack-notifications
      # Utilize Fan-in process for notification execution
      - workflow-success:
          context: slack-notifications
          requires:
            - build-test-and-notify
            - build-test-and-notify-2
            - build-test-and-notify-3