version: 2.1
orbs:
  node: circleci/node@4.7.0
  slack: circleci/slack@4.4.4
jobs:
  build-test-and-notify:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run: npm test
      - slack/notify:
          event: pass
          mentions: '@josh.jimenez'
          template: basic_success_1
      - slack/notify:
          event: fail
          mentions: "@josh.jimenez"
          template: basic_fail_1
workflows:
  build-and-notify:
    jobs:
      - build-test-and-notify
          context: slack-notifications