version: 2.1
orbs:
  node: circleci/node@4.7.0
  slack: circleci/slack@4.4.4
jobs:
  build-test-and-notify:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run: npm test
      - slack/notify:
        color: "#42e2f4"
        mentions: "josh.jimenez"
        message: A custom message to notify the channel about the latest build
      - slack/status:
        fail_only: true
        mentions: "josh.jimenez"
workflows:
  build-and-notify:
    jobs:
      - build-test-and-notify