version: 2.1

orbs:
  node: circleci/node@4.7.0
  slack: circleci/slack@4.4.4

commands:
  slack-status:
    steps:
      - slack/notify:
          event: pass
          mentions: '@channel'
          template: basic_success_1

  slack-fail:
    steps:
      - slack/notify:
          event: fail
          mentions: "@channel"
          template: basic_fail_1

jobs:
  build-test-and-notify:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run: npm test
      - slack-fail
      
  build-test-and-notify-2:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run: npm test
      - slack-fail

  workflow-success:
    executor:
      name: node/default
    steps:
      - run:
          name: Success
          command: | 
            exit 0
      - slack-success
workflows:
  build-and-notify:
    jobs:
      - build-test-and-notify:
          context: slack-notifications
      - build-test-and-notify-2:
          context: slack-notifications
      - workflow-success:
          context: slack-notifications
        requires:
          - build-test-and-notify
          - build-test-and-notify-2